name: Build Desktop JAR

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build JAR with dist task
        run: ./gradlew :lwjgl3:dist

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: AsteroidsDesktopJar
          path: lwjgl3/build/libs/*.jar
